In [ ]:
# default_exp layers

In [ ]:
#export
import torch
from torch import nn

In [ ]:
input = torch.randn((64,512,5,5))

In [ ]:
ad = nn.AdaptiveAvgPool2d(1)

In [ ]:
rad = ad(input)

In [ ]:
ad_concat_pool = AdaptiveConcatPool2d(1)

In [ ]:
r = ad_concat_pool(input)

In [ ]:
r.shape

torch.Size([64, 1024, 1, 1])

In [ ]:
rad.shape

torch.Size([64, 512, 1, 1])

In [ ]:
r[0, :512]

tensor([[[3.5989]],

        [[1.3792]],

        [[1.9514]],

        [[2.3894]],

        [[2.1806]],

        [[2.0603]],

        [[1.4965]],

        [[1.6783]],

        [[2.9830]],

        [[1.1461]],

        [[1.5264]],

        [[2.1015]],

        [[2.2456]],

        [[2.2104]],

        [[1.9561]],

        [[2.1702]],

        [[1.9113]],

        [[2.5032]],

        [[2.3942]],

        [[1.8280]],

        [[1.8230]],

        [[3.0390]],

        [[2.1085]],

        [[2.2420]],

        [[2.0004]],

        [[2.0202]],

        [[1.8579]],

        [[1.7786]],

        [[2.2132]],

        [[2.0115]],

        [[1.5750]],

        [[2.4011]],

        [[2.1038]],

        [[2.8242]],

        [[2.0532]],

        [[1.6745]],

        [[2.4546]],

        [[2.2864]],

        [[1.4300]],

        [[1.8565]],

        [[2.1390]],

        [[1.7880]],

        [[2.5538]],

        [[1.4457]],

        [[1.8534]],

        [[2.3647]],

        [[1.6627]],

        [[1.9

In [ ]:
r[0, 512:]

tensor([[[ 0.1671]],

        [[-0.1741]],

        [[ 0.2836]],

        [[-0.1569]],

        [[ 0.3075]],

        [[ 0.0244]],

        [[ 0.1575]],

        [[-0.1142]],

        [[-0.1408]],

        [[-0.2690]],

        [[-0.3078]],

        [[ 0.3076]],

        [[ 0.0404]],

        [[-0.0798]],

        [[-0.0705]],

        [[-0.2138]],

        [[ 0.1125]],

        [[-0.0318]],

        [[ 0.1701]],

        [[-0.1704]],

        [[-0.2065]],

        [[ 0.3068]],

        [[ 0.0032]],

        [[-0.0684]],

        [[ 0.1890]],

        [[-0.0383]],

        [[ 0.1216]],

        [[-0.1684]],

        [[ 0.2139]],

        [[ 0.2081]],

        [[ 0.0013]],

        [[ 0.4855]],

        [[ 0.0906]],

        [[ 0.3606]],

        [[ 0.0063]],

        [[-0.0013]],

        [[-0.0878]],

        [[ 0.0815]],

        [[-0.3650]],

        [[ 0.2933]],

        [[-0.1595]],

        [[ 0.1899]],

        [[ 0.2226]],

        [[ 0.0641]],

        [[ 0.3335]],

        [[

In [ ]:
rad[0]

tensor([[[ 0.1671]],

        [[-0.1741]],

        [[ 0.2836]],

        [[-0.1569]],

        [[ 0.3075]],

        [[ 0.0244]],

        [[ 0.1575]],

        [[-0.1142]],

        [[-0.1408]],

        [[-0.2690]],

        [[-0.3078]],

        [[ 0.3076]],

        [[ 0.0404]],

        [[-0.0798]],

        [[-0.0705]],

        [[-0.2138]],

        [[ 0.1125]],

        [[-0.0318]],

        [[ 0.1701]],

        [[-0.1704]],

        [[-0.2065]],

        [[ 0.3068]],

        [[ 0.0032]],

        [[-0.0684]],

        [[ 0.1890]],

        [[-0.0383]],

        [[ 0.1216]],

        [[-0.1684]],

        [[ 0.2139]],

        [[ 0.2081]],

        [[ 0.0013]],

        [[ 0.4855]],

        [[ 0.0906]],

        [[ 0.3606]],

        [[ 0.0063]],

        [[-0.0013]],

        [[-0.0878]],

        [[ 0.0815]],

        [[-0.3650]],

        [[ 0.2933]],

        [[-0.1595]],

        [[ 0.1899]],

        [[ 0.2226]],

        [[ 0.0641]],

        [[ 0.3335]],

        [[

# Layers

## Pooling

In [ ]:
#export

#From fastai library
class AdaptiveConcatPool2d(torch.nn.Module):
    "Layer that concats `AdaptiveAvgPool2d` and `AdaptiveMaxPool2d`."
    def __init__(self, sz = None):
        "Output will be 2*sz or 2 if sz is None"
        super().__init__()
        self.output_size = sz or 1
        self.ap = nn.AdaptiveAvgPool2d(self.output_size)
        self.mp = nn.AdaptiveMaxPool2d(self.output_size)

    def forward(self, x): return torch.cat([self.mp(x), self.ap(x)], 1)

# Tests

In [ ]:
from nbdev.export import *
notebook2script()


Converted 00_core.ipynb.
Converted 01_utils.ipynb.
Converted 02_training.ipynb.
Converted index.ipynb.
